# Generated by Django 3.0.3 on 2020-04-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='contactdetail',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='contactdetail',
            name='passport_id',
        ),
    ]
