# Generated by Django 3.0.3 on 2020-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='phone_number',
            field=models.CharField(default='0002', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='street_address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='town_or_city',
            field=models.CharField(max_length=40),
        ),
    ]
