# Generated by Django 3.0.3 on 2020-03-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200330_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
