# Generated by Django 3.0.3 on 2020-05-29 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPassenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('birth_day', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('citizenship', django_countries.fields.CountryField(max_length=2)),
                ('passport_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_number', models.PositiveIntegerField()),
                ('confirmation_status', models.BooleanField(default=False)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('other_passenger', models.ManyToManyField(blank=True, to='checkout.OtherPassenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Trip')),
                ('user_passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Passenger')),
            ],
        ),
    ]
