# Generated by Django 3.0.3 on 2020-05-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_status', models.BooleanField(default=False)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('other_passenger', models.ManyToManyField(blank=True, to='checkout.OtherPassenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Trip')),
                ('user_passenger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Passenger')),
            ],
        ),
    ]
