# Generated by Django 3.0.3 on 2020-05-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200517_0900'),
        ('checkout', '0002_bookingreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreference',
            name='user_passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Passenger'),
        ),
    ]
