# Generated by Django 3.0.3 on 2020-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('date', models.ManyToManyField(to='trips.Date')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='trip_pics')),
            ],
            options={
                'ordering': ['img_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('description', models.TextField()),
                ('distance', models.IntegerField()),
                ('departure', models.ManyToManyField(to='trips.Departure')),
                ('img', models.ManyToManyField(to='trips.TripImage')),
                ('required_document', models.ManyToManyField(to='trips.RequiredDocument')),
            ],
        ),
    ]
