# Generated by Django 3.0.3 on 2020-03-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('price', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('slot', models.IntegerField()),
                ('description', models.TextField()),
                ('distance', models.IntegerField()),
                ('img', models.FileField(blank=True, upload_to='')),
                ('departure_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.DepartureSite')),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.RequiredDocument')),
            ],
        ),
    ]
