# Generated by Django 3.0.3 on 2020-05-21 09:21

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('site_code', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50)),
                ('img_file', models.ImageField(blank=True, upload_to='trip_pics')),
            ],
            options={
                'ordering': ['img_name'],
            },
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('destination_code', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('img', models.ManyToManyField(to='trips.TripImage')),
                ('required_document', models.ManyToManyField(to='trips.RequiredDocument')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('slot', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.TripCategory')),
                ('departure_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.DepartureSite')),
            ],
        ),
    ]
