# Generated by Django 3.0.7 on 2020-08-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['departure_date']},
        ),
        migrations.AlterModelOptions(
            name='tripcategory',
            options={'ordering': ['destination'], 'verbose_name_plural': 'Trip Categories'},
        ),
    ]
