# Generated by Django 3.0.3 on 2020-03-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripimage',
            options={'ordering': ['img_name']},
        ),
    ]
