# Generated by Django 3.0.3 on 2020-06-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requireddocument',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['departure_date']},
        ),
        migrations.AlterModelOptions(
            name='tripcategory',
            options={'ordering': ['destination']},
        ),
    ]
