# Generated by Django 3.0.3 on 2020-04-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryTrip',
            new_name='TripCategory',
        ),
    ]
